apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: formless
resources:
  - namespace.yaml
  - api-secrets.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
